### ISSUE TITLE
CRANcompliance: reference to deSolve incorrect

### ISSUE THREAD

**Issue by bmarkslash7** [bmarkslash7/QPot#11]
from devtools::check()

checking Rd cross-references ... WARNING
Missing link or links in documentation object 'TSTraj.Rd':
  ‘deSolve’

See section 'Cross-references' in the 'Writing R Extensions' manual.

**Comment by dispersing** [comment]
Reference was to like to a function in another package, rather than the package.  That is:
\code{\link{deSolve}}, rather than \href{https://cran.r-project.org/web/packages/deSolve/index.html}{deSolve} .
