### ISSUE TITLE
TODO: Check QPotential with different bounds

### ISSUE THREAD

**Issue by dispersing** [bmarkslash7/QPot#39]
All of our tests have included `x.bound` = `y.bound`.  Run `QPotential()` where `x.bound` != `y.bound`.

**Comment by dispersing** [comment]
Ran several tests--works.  Attached is an example with the `x.bound = c(-0.5, 10)` and `y.bound = c(-0.5, 5)`.  (The step sizes are equal and set to 1000 in this example, that it's plotted in `QPContour()` with a `dens = c(500, 500)`.
![screen shot 2015-09-13 at 3 31 23 pm](https://cloud.githubusercontent.com/assets/8403411/9838511/4ed209f8-5a2d-11e5-8ba0-3a7c12c19b6f.png)

**Comment by bmarkslash7** [comment]
Thanks for doing this!
