### ISSUE TITLE
Con el -Wall activado...

### ISSUE THREAD

**Issue by alexciru** [bmarkslash7/QPot#45]
He arreglado el makefile para que use los flags, la cosa es que aparecen muchos mas warning(lo esperado). LA pregunta es si edito la rama de la 1º literacion o el master para tenerlo bien en esta suganda literacion.

La cosa es que como estamos creando archivos y tal, a lo mejor ni siquiera compila para que aparezcan los nuevos warnings.

![warnings_wall](https://cloud.githubusercontent.com/assets/25507220/23265352/a168a8f4-f9e4-11e6-8a11-a4b6a06bd6f4.png)

**Comment by bmarkslash7** [comment]
This is not our code.

Your warnings are based on comments within comments (/* comment /* something */ something */), unused variables, and redefinitions (probably due to a header file being loaded multiple times).

**Comment by alexciru** [comment]
Lol, i dont know how I got there, my bad.

**Comment by bmarkslash7** [comment]
No problems!  Good luck getting those warnings fixed.
