### ISSUE TITLE
Suggest books/resources for learning Stochastic Differential Equation Quasi-Potential Analysis.

### ISSUE THREAD

**Issue by Jeet1994** [bmarkslash7/QPot#46]
Hello, came across your paper in the [r-journal](https://journal.r-project.org/archive/2016-2/moore-stieha-nolting-etal.pdf) site. 
It looks **highly sophisticated because of all the math running** into it, I would be grateful if you could **help me with the names of some resources for me to get started with the topic**. 
Thank you. :bowtie:

**Comment by bmarkslash7** [comment]
Hi Jeet1994,
What is your background and interest?  The R Article has a lot of references that will get you started, whether it is specifically about the quasi-potential or about stochastic differential equations themselves.  I come from an ecology background, so the books I would recommend may not be books that are applied to your interests.
-chris

**Comment by Jeet1994** [comment]
I am a Petrochemical Engineer; I just want to learn the math. :smile:

**Comment by dispersing** [comment]
Hi @Jeet1994 

For specific reference on quasipotentials for nongratient SDEs, these should be useful
1. B. C. Nolting and K. C. Abbott. Balls, cups, and quasi-potentials: Quantifying stability in stochastic systems. Ecology, 97(4):850–864, 2016.
2. M. K. Cameron. Finding the quasipotential for nongradient SDEs. Physica D, 241(18):1532–1550, 2012.

For general references on SDEs, these should be useful

3. E. J. Allen. Modeling with Ito Stochastic Differetnial Equations, volume 22 of Mathematical Modeling: Theory and Applications. Springer-Verlag, 2007.
4. S. M. Iacus. Simulation and Inference for Stochastic Differential Equations: With R Examples, volume 1. Springer Science & Business Media, 2009.

Thanks for reading the paper and contacting us!

Chris
